# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "229cebcffaa8b246ab037f4524aa36cf"
application_url = "https://hospital-event-arena-salem.trycloudflare.com"
embedded = true
name = "Tradie X Apparel21"
handle = "tradie-x-apparel21-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ratul-practices.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_payment_terms,read_products,write_customers,write_inventory,write_locations,write_orders,write_payment_terms,write_products"

[auth]
redirect_urls = [
  "https://hospital-event-arena-salem.trycloudflare.com/auth/callback",
  "https://hospital-event-arena-salem.trycloudflare.com/auth/shopify/callback",
  "https://hospital-event-arena-salem.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
